name: New Script1

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy

    steps:
      - uses: actions/checkout@master

      - name: Bucket actions
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - run: npm i
      - run: npm install newman

      
      - name: Publish
        uses: nogsantos/scp-deploy@master
        with:
          src: ./*
          host: ${{ secrets.SSH_HOST }}
          remote: ${{ secrets.SSH_DIR }}
          port: 22
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
