name: Test, Create Report and Publish result

on:
  schedule:
     - cron:  '*/10 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy

    steps:
      - uses: actions/checkout@master

      - name: Bucket actions
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - run: npm i
      - run: npm install -g newman
      - run: npm install -g newman-reporter-htmlextra
      - run: newman run ./api-test.json -x -r htmlextra --reporter-htmlextra-export ./reports/index.html

      
      - name: Publish
        uses: appleboy/scp-action@master
        with:
          host: 35.233.168.216
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "./reports/index.html"
          target: "report"
      
      - name: Copy arttifact and Restart Server
        uses: appleboy/ssh-action@master
        with:
         host: 35.233.168.216
         username: ubuntu
         key: ${{ secrets.SSH_KEY }}
         port: 22
         script: ./refresh.sh
