name: New Script1

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy

    steps:
      - uses: actions/checkout@master

      - name: Bucket actions
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - run: npm i
      - run: npm install newman

      
      - name: Publish
        uses: appleboy/scp-action@master
        with:
          host: 185.205.47.193 
          username: ubuntu
          password: rigpa53
          port: 22
          source: "./api-test.json"
          target: "test"
